# -*- coding: utf-8 -*-
"""train-yolov8-object-detection-on-custom-dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/roboflow/notebooks/blob/main/notebooks/train-yolov8-object-detection-on-custom-dataset.ipynb
"""

!pip install ultralytics

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="DEIN_ROBOFLOW_API_KEY_HIER_EINFUEGEN")
project = rf.workspace("gianni-mwuu5").project("basketballplatze-osm-yolo")
version = project.version(1)
dataset = version.download("yolov8")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")   # kleinstes Modell, reicht für eine Klasse
results = model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=100,
    imgsz=640,
    batch=16
)

model.export(format="tflite")

metrics = model.val()
print(metrics.box.map50, metrics.box.map)

from google.colab import files
files.download("/content/runs/detect/train/weights/best.tflite")